version: '3.9'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data2:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - 5432:5432
  ui:
    build: ./react-app
    command: npm start
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
  airflow-db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - 5433:5432
  airflow:
    build: ./airflow
    ports:
      - "8080:8080"
    depends_on:
      - airflow-db
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@airflow-db:5432/airflow
    env_file:
      - ./.env.dev


volumes:
  postgres_data2:
  postgres_data:

