# Generated by Django 3.2.6 on 2023-03-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usr_date_joined',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usr_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usr_is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usr_is_admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usr_is_deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usr_is_staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usr_org_id',
            new_name='org_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usr_password',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usr_token',
        ),
    ]
