# Generated by Django 3.2.6 on 2023-03-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230318_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizaton',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=50)),
                ('org_secret_key', models.CharField(max_length=50)),
            ],
        ),
    ]
