# Generated by Django 3.2.6 on 2023-03-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_organizaton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizaton',
            new_name='Organization',
        ),
    ]
