# Generated by Django 3.2.6 on 2023-03-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20230318_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
