
export const Routes = {
    // pages
    Presentation: { path: "/" },
    DashboardOverview: { path: "/dashboard/overview" },
    Transactions: { path: "/transactions" },
    Settings: { path: "/settings" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Billing: { path: "/billing" },
    Invoice: { path: "/invoice" },
    Signin: { path: "/sign-in" },
    Signup: { path: "/sign-up" },
    Organization: { path: "/organization" },
    ForgotPassword: { path: "/forgot-password" },
    ResetPassword: { path: "/reset-password" },
    Lock: { path: "/lock" },
    NotFound: { path: "/404" },
    ServerError: { path: "/500" },
    Configuration: {path: "/recommend/configuration"},
    Recommend: {path: "/recommend/recommend-api"},
    Analytics2: {path: "/data-analytics2"},
    Analytics: {path: "/data-analytics/"},
    Documentation: {path: "/documentation"},
    Profile: {path: "/profile"},
    ItemDetail: {path: "/data-management/detail/"},

    Customer: { path: "customer"},
    Event: { path: "event"},
    Transaction: { path: "transaction"},
    Product: { path: "product" },
    Item: { path: "item" },
    EventItem: { path: "event_item" },
    TransactionItem: { path: "transaction_item" },
    Behavior: {path: "behavior"},
    // ImportHistory: { path: "/data-management/list/importhistory"},
    ListItems: { path: "/data-management/list/" },
    MatchingTemplate: { path: "/data-management/matching-template"},
    NewTemplate: { path: "/data-management/new-template"},
    DetailTemplate: { path: "/data-management/detail-template"},

    ImportAPI: { path: "/data-management/import-api/" },
    ImportFile: { path: "/data-management/import-file/" },
    ImportHistory: { path: "/data-management/import-history"},
    DeleteItems: { path: "/data-management/delete-items/"},

    ListModels: {path: "/data-knowledge/list/"},
    ModelDetail: {path: "/data-knowledge/detail/"},
    ModelRun: {path: "/data-knowledge/run/"},
    TestAPI: {path: "/data-knowledge/test-api/"},
    CustomerSegmentation: { path: "customer-segmentation"},
    ProductRecommendation: { path: "product-recommendation"},
    AssociationRule: { path: "association-rule"},
    Correlation: { path: "correlation"},

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};